### ISSUE TITLE
Repeat of issue 4

### ISSUE THREAD

**Issue by businessBoris** [dpoetzsch/keyman#5]
I have to say what a lovely idea for an extension, well done. I'm currently probably doing what inspired this extension; thank you.

Same issue as #4 I think: 

Has your new version made it to the general extensions.gnome.org repo yet? It's been a week since you closed it, so I would think so.

This morning's  journalctl output:

```
May 20 10:10:39  gnome-shell[2060]: JS WARNING: [/home/alex/.local/share/gnome-shell/extensions/keyman@dpoetzsch.github.com/keyman.js 115]: reference to undefined property "MESSAGE_TRAY"
May 20 10:10:39 zurich gnome-shell[2060]: Extension "keyman@dpoetzsch.github.com" had error: TypeError: this._createLayout is not a function
May 20 10:51:03 zurich gnome-shell[2060]: Extension "keyman@dpoetzsch.github.com" had error: TypeError: keyman is undefined
May 20 10:51:03 zurich gnome-shell[2060]: Extension "keyman@dpoetzsch.github.com" had error: TypeError: this._createLayout is not a function
<snip>

```

The last error is reported repeatedly for only the single second in which it occurs 10:51:03. It is not in my error log after that, although the machine has been on all day.

Specs:
Standard Fedora 30 stable.
Gnome Version 3.32.2
Intel Haswell Desktop 64bit Intel processor; loads of RAM.

**Comment by dpoetzsch** [comment]
Actually this was a new issue. I can reproduce it on my machine and fixed it locally. I will release the fix today.

**Comment by businessBoris** [comment]
Just a note to say thank you for your time and effort.
Keyman just appear correctly on my machine today working AFAICT. I updated it yesterday.
Might be worthwhile including a note to restart the shell or something after the new version.

**Comment by dpoetzsch** [comment]
Thanks for your feedback :)
