### ISSUE TITLE
Stopped working on Ubuntu 19.10/GNOME 3.34

### ISSUE THREAD

**Issue by linuxturtle** [dpoetzsch/keyman#9]
Here is some info from the log which might help..

`Nov  1 15:19:48 vera gnome-shell[1945]: Some code accessed the property 'KeyMan' on the module 'keyman'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.`

`Nov  1 15:19:48 vera gnome-shell[1945]: Some code accessed the property 'History' on the module 'data'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.`

`Nov  1 15:19:48 vera gnome-shell[1945]: Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to explicitly call ByteArray.toString(array).#012(Note that array.toString() may have been called implicitly.)#0120 _load() ["/home/brett/.local/share/gnome-shell/extensions/keyman@dpoetzsch.github.com/data.js":24]#0121 History() ["/home/brett/.local/share/gnome-shell/extensions/keyman@dpoetzsch.github.com/data.js":41]#0122 KeyMan() ["/home/brett/.local/share/gnome-shell/extensions/keyman@dpoetzsch.github.com/keyman.js":95]#0123 enable() ["/home/brett/.local/share/gnome-shell/extensions/keyman@dpoetzsch.github.com/extension.js":28]#0124 _callExtensionEnable() ["resource:///org/gnome/shell/ui/extensionSystem.js":132]#0125 loadExtension() ["resource:///org/gnome/shell/ui/extensionSystem.js":264]#0126 callback() ["resource:///org/gnome/shell/ui/extensionDownloader.js":244]#0127 gotExtensionZipFile/<() ["resource:///org/gnome/shell/ui/extensionDownloader.js":108]`

`Nov  1 15:19:48 vera gnome-shell[1945]: Usage of object.actor is deprecated for PanelMenuButton#012get@resource:///org/gnome/shell/ui/environment.js:242:29#012KeyMan@/home/brett/.local/share/gnome-shell/extensions/keyman@dpoetzsch.github.com/keyman.js:106:9#012enable@/home/brett/.local/share/gnome-shell/extensions/keyman@dpoetzsch.github.com/extension.js:28:14#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:132:13#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:264:21#012callback@resource:///org/gnome/shell/ui/extensionDownloader.js:244:17#012gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:108:13`

`Nov  1 15:19:48 vera gnome-shell[1945]: JS ERROR: Extension keyman@dpoetzsch.github.com: TypeError: this._addIcon is not a function#012CollectionItem@/home/brett/.local/share/gnome-shell/extensions/keyman@dpoetzsch.github.com/keyman.js:55:9#012_populateCollectionsMenu@/home/brett/.local/share/gnome-shell/extensions/keyman@dpoetzsch.github.com/keyman.js:191:21#012_createLayout@/home/brett/.local/share/gnome-shell/extensions/keyman@dpoetzsch.github.com/keyman.js:200:9#012KeyMan@/home/brett/.local/share/gnome-shell/extensions/keyman@dpoetzsch.github.com/keyman.js:131:9#012enable@/home/brett/.local/share/gnome-shell/extensions/keyman@dpoetzsch.github.com/extension.js:28:14#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:132:13#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:264:21#012callback@resource:///org/gnome/shell/ui/extensionDownloader.js:244:17#012gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:108:13`

**Comment by businessBoris** [comment]
Great little extension. Thank you very much, @dpoetzsch

**Comment by dpoetzsch** [comment]
Thank you for the detailed issue. I'll try to install a recent ubuntu and fix this error. Very annoying that JS support is so broken in gnome..

**Comment by linuxturtle** [comment]
Awesome, thank you @dpoetzsch!  The first 4 lines are deprecation warnings, so I tried to figure out how to fix the last line (which seems to indicate that PopupMenuItem._addIcon() no longer exists).  But since I have no clue what I'm doing, all I did was crash gnome-shell hard enough to require a reboot multiple times :laughing:  I assume this problem is a result of Gnome 3.4, not Ubuntu proper.
